name: pull_request_on_master
run-name: Pull Request Merged on Master
on:
    pull_request:
        types:
            - closed
        branches:
            - master
jobs:
    pull-request-on-master:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - run: npm install -g bats
            - run: bats -v
