name: php-version
run-name: checking php version
on: push
jobs:
    check-php-version:
        runs-on: ubuntu-latest
        steps:
            - name: checkout to runner
              uses: actions/checkout@v3
            - name: install php
              uses: php-actions/phpcs@v1
              with:
                php_version: 8.1
                path: src/
            - name: check php version
              run: php -v
            