name: learn-github-action
run-name: ${{github.actor}} is learning github action
on: 
    push:
        branches:
            - develop
jobs:
    checks-bat-version:
        runs-on: ubuntu-latest
        steps:
            - name: checkout to runner
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: '14'
            - name: install bats
              run: npm install -g bats
            - name: checks bat version
              run: bats -v